"""vaultlab.report.html — single-file HTML report renderer.

Public entrypoint: ``render_report(title, sections, theme, ...) -> str``.

The output is a self-contained HTML document — inline CSS, inline JS, no
external assets. Save the string to a ``.html`` file and open in any browser.

Background: see ``SKILL.md`` in this package + Thariq Shihipar,
"The Unreasonable Effectiveness of HTML" (Anthropic, 2026) for the design
rationale.
"""

from __future__ import annotations

import html as _html
from datetime import datetime
from pathlib import Path
from typing import Literal

from vaultlab.report._css import CSS
from vaultlab.report._js import JS

Theme = Literal["light", "dark", "auto"]


def render_report(
    title: str,
    sections: list[str],
    *,
    eyebrow: str | None = None,
    subtitle: str | None = None,
    meta: str | None = None,
    theme: Theme = "light",
    include_js: bool = True,
    footer: str | None = None,
    lang: str = "en",
) -> str:
    """Render a complete HTML report document.

    Parameters
    ----------
    title:
        Report title (becomes the <title> + <h1>).
    sections:
        Pre-rendered HTML strings (typically from
        :mod:`vaultlab.report.components`). Joined verbatim into the body.
    eyebrow:
        Small uppercase label above the title (e.g., "vaultlab · audit").
    subtitle:
        Subtitle line under the H1.
    meta:
        Free-form HTML to render in the header meta band (e.g., dates,
        repo refs, source links).
    theme:
        "light", "dark", or "auto" (uses prefers-color-scheme).
    include_js:
        Whether to bundle the interactive JS. Set False for static reports.
    footer:
        Optional footer HTML.
    lang:
        ``lang`` attribute on <html>.

    Returns
    -------
    str
        A complete, self-contained HTML document string.
    """
    theme_attr = ""
    if theme == "dark":
        theme_attr = ' data-theme="dark"'
    elif theme == "auto":
        # CSS handles via @media (prefers-color-scheme: dark) — not bundled
        # by default. Caller may inject custom CSS for full auto handling.
        pass

    eyebrow_html = f'<div class="eyebrow">{_html.escape(eyebrow)}</div>' if eyebrow else ""
    subtitle_html = (
        f'<div style="color:var(--muted);font-size:15px;margin:4px 0 8px;">'
        f"{_html.escape(subtitle)}</div>"
        if subtitle
        else ""
    )
    meta_html = f'<div class="meta">{meta}</div>' if meta else ""
    js_block = f"<script>{JS}</script>" if include_js else ""
    footer_html = (
        f'<footer class="vl-foot">{footer}</footer>'
        if footer
        else (
            '<footer class="vl-foot">'
            f"Generated by vaultlab.report · {datetime.now():%Y-%m-%d %H:%M}"
            "</footer>"
        )
    )

    return f"""<!doctype html>
<html lang="{_html.escape(lang)}"{theme_attr}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_html.escape(title)}</title>
<style>{CSS}</style>
</head>
<body>
<div class="vl-wrap">
<header class="vl-head">
{eyebrow_html}
<h1>{_html.escape(title)}</h1>
{subtitle_html}
{meta_html}
</header>
{chr(10).join(sections)}
{footer_html}
</div>
{js_block}
</body>
</html>
"""


def write_report(
    path: str | Path,
    title: str,
    sections: list[str],
    **kwargs,
) -> Path:
    """Render and write the report to ``path``. Returns the resolved Path."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render_report(title, sections, **kwargs), encoding="utf-8")
    return p


__all__ = ["render_report", "write_report", "Theme"]
