"""``vaultlab demo`` — produce a real audit-clean artifact from bundled sample data.

This subcommand is the load-bearing enabler for the north-star
time-to-first-artifact criterion: a fresh user runs ``pip install
vaultlab && vaultlab demo`` cold and lands on a real .pptx + provenance
sidecars in well under five minutes, without any API keys, network
calls, or knobs to turn.

The demo composes a small journal-club deck about one bundled real
open-access paper (metadata + synthetic figures shipped inside the
package). It uses the same low-level slide composer
(:func:`vaultlab.slides.deck.build_deck`) and provenance writer
(:func:`vaultlab.provenance.write_receipts`) that the production
pipeline uses — the artifact is not a mock; it's a real vaultlab
output with a real receipt that ``vaultlab list-policy-skipped`` and
``vaultlab paperclip-grep`` callers can inspect with the same tools.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import time
from importlib import resources
from pathlib import Path
from typing import Any

DEFAULT_OUT_DIR = "./vaultlab-demo-out"
DECK_FILENAME = "deck.pptx"


# ---------------------------------------------------------------------------
# Bundled-data lookup
# ---------------------------------------------------------------------------


def _bundled_data_root() -> Path:
    """Return the on-disk path of ``src/vaultlab/data/demo/``.

    Uses ``importlib.resources`` so this works for both editable installs
    (src layout) and wheel-installed copies (where the path resolves
    inside the site-packages tree). The ``as_file`` context manager is
    not needed here because we ship plain files (not zipped resources).
    """
    return Path(resources.files("vaultlab.data.demo"))  # type: ignore[arg-type]


def _bundled_paper_path() -> Path:
    return _bundled_data_root() / "paper.json"


def _bundled_figures_dir() -> Path:
    return _bundled_data_root() / "figures"


# ---------------------------------------------------------------------------
# Deck plan composition (no LLM — pure Python + bundled metadata)
# ---------------------------------------------------------------------------


def _build_plan_from_paper(
    paper: dict[str, Any],
    figure_paths: list[Path],
) -> Any:
    """Compose a deterministic 5-6 slide journal-club ``DeckPlan``.

    No LLM call, no network. The bullets come straight from the
    bundled ``paper.json`` (``key_claims``, ``discussion_questions``,
    etc.) so the demo is byte-stable across runs and trivially
    auditable.
    """
    # Lazy import — keeps ``vaultlab.cli.demo`` importable without
    # python-pptx installed (the heavy lift only fires when ``run_demo``
    # actually calls ``build_deck``).
    from vaultlab.slides.deck import DeckPlan, DeckSlide

    title = paper.get("title", "Demo journal-club deck")
    authors = paper.get("authors") or ["(unknown author)"]
    year = paper.get("year", "")
    doi = paper.get("doi", "")
    journal = paper.get("journal", "")
    abstract = paper.get("abstract", "")
    key_claims = list(paper.get("key_claims") or [])
    discussion_qs = list(paper.get("discussion_questions") or [])

    short_cite_authors = (
        f"{authors[0].split()[-1]} et al." if len(authors) > 1 else authors[0]
    )
    short_cite = f"{short_cite_authors} {year} — {journal}".strip(" —")

    sections = ["Context", "Findings", "Discussion"]

    slides: list[DeckSlide] = []

    # --- 1. Title slide -----------------------------------------------------
    slides.append(
        DeckSlide(
            kind="title",
            title=title,
            content={
                "subtitle": short_cite,
                "speaker": "vaultlab demo",
                "affiliation": "Generated by `vaultlab demo`",
                "date": time.strftime("%Y-%m-%d"),
            },
            notes=(
                "Demo deck generated by `vaultlab demo`. Source paper metadata "
                "ships inside the package; figures are synthetic illustrations "
                "produced by matplotlib (no source-paper figures reproduced)."
            ),
        )
    )

    # --- 2. Context (section_intro) -----------------------------------------
    slides.append(
        DeckSlide(
            kind="section_intro",
            title="Why this paper matters",
            content={
                "section_name": "Context",
                "key_question": (
                    "Are immune-tissue motifs a fixed vocabulary that disease "
                    "rewires, or do tumors invent new spatial states?"
                ),
                "bullets": [
                    "Multiplexed imaging (e.g. CODEX) now resolves dozens of "
                    "markers at single-cell resolution.",
                    "Cellular neighborhoods — not individual cells — explain "
                    "tissue function and disease state.",
                    "Open question: how conserved are these neighborhoods "
                    "across tissues and disease contexts?",
                ],
            },
        )
    )

    # --- 3. Figure 1 (cellular neighborhoods) -------------------------------
    if len(figure_paths) >= 1:
        slides.append(
            DeckSlide(
                kind="figure",
                title="Cellular neighborhoods form a discrete catalogue",
                content={
                    "figure_path": figure_paths[0],
                    "annotations": [],
                    "motif_colors": {},
                    "caption": (
                        "Figure 1 (synthetic demo). Five motif-like clusters "
                        "of cell types emerge from CODEX-style spatial data; "
                        "uncommitted cells (grey) fill the interstitium."
                    ),
                    "citation_doi": doi,
                },
                notes=(
                    "Talking points:\n"
                    " - Five motifs cover most of the tissue area; "
                    "interstitial cells are the minority.\n"
                    " - Motifs are spatially compact — neighborhood "
                    "analysis is tractable with simple clustering."
                ),
            )
        )

    # --- 4. Findings (bullets) ----------------------------------------------
    if key_claims:
        slides.append(
            DeckSlide(
                kind="bullets",
                title="Key findings",
                content={
                    "bullets": key_claims,
                    "citations": [doi] if doi else [],
                },
                notes=(
                    "Walk each bullet in order. The third bullet motivates "
                    "the panel-design discussion in the next section."
                ),
            )
        )

    # --- 5. Figure 2 (motif frequencies) ------------------------------------
    if len(figure_paths) >= 2:
        slides.append(
            DeckSlide(
                kind="figure",
                title="Tumors rewire — they do not invent — motifs",
                content={
                    "figure_path": figure_paths[1],
                    "annotations": [],
                    "motif_colors": {},
                    "caption": (
                        "Figure 2 (synthetic demo). Motif frequencies in "
                        "normal vs tumor tissue. The same five motifs cover "
                        "both; their relative weights shift."
                    ),
                    "citation_doi": doi,
                },
                notes=(
                    "Lead the discussion: if motifs are conserved, what's the "
                    "minimal vocabulary needed to describe tumor immune evasion?"
                ),
            )
        )

    # --- 6. Discussion ------------------------------------------------------
    if discussion_qs:
        slides.append(
            DeckSlide(
                kind="bullets",
                title="Discussion questions",
                content={
                    "bullets": discussion_qs,
                    "citations": [],
                },
                notes=(
                    "These are bundled in `paper.json` under "
                    "`discussion_questions`. Edit the file (or its in-KB "
                    "counterpart) and re-run `vaultlab demo` to refresh."
                ),
            )
        )

    # --- 7. References ------------------------------------------------------
    slides.append(
        DeckSlide(
            kind="references",
            title="References",
            content={
                "refs": [
                    {
                        "n": 1,
                        "citation": (
                            f"{', '.join(authors)}. {title}. "
                            f"{journal} ({year}). doi:{doi}"
                        ),
                        "doi": doi,
                    }
                ]
            },
        )
    )

    return DeckPlan(
        title=title,
        subtitle=short_cite,
        speaker="vaultlab demo",
        affiliation="Generated by `vaultlab demo`",
        sections=sections,
        slides=slides,
        theme="default",  # avoid Hickey-Lab template requirement for first-run users
    )


# ---------------------------------------------------------------------------
# Provenance — small wrapper so we don't depend on full pipeline machinery
# ---------------------------------------------------------------------------


def _write_demo_provenance(
    deck_path: Path,
    paper: dict[str, Any],
    figure_paths: list[Path],
    elapsed_s: float,
) -> tuple[Path, Path]:
    from vaultlab.provenance import ProvenanceRecord, write_receipts

    try:
        import vaultlab as _vl

        version = getattr(_vl, "__version__", "unknown")
    except Exception:  # pragma: no cover — version lookup is best-effort
        version = "unknown"

    record = ProvenanceRecord(
        generated_by="vaultlab.cli.demo.run_demo",
        project="vaultlab-demo",
        topic=paper.get("topic", "Demo journal-club deck"),
        kind="slide_deck",
        inputs=[str(_bundled_paper_path()), *(str(p) for p in figure_paths)],
        code_version=version,
        params={
            "deck_filename": deck_path.name,
            "paper_doi": paper.get("doi", ""),
            "paper_title": paper.get("title", ""),
            "n_figures": len(figure_paths),
            "elapsed_s": round(elapsed_s, 3),
            "offline": True,
            "llm_used": False,
        },
        tags=["demo", "journal-club", "deck"],
        notes=(
            "Generated by `vaultlab demo`. No network calls or LLM invocations. "
            "The deck plan is composed deterministically from bundled "
            "`paper.json` metadata; figures are synthetic, generated by "
            "`vaultlab.data.demo._generate_demo_figures` and committed to the "
            "package. This sidecar is byte-stable except for the `generated_at` "
            "timestamp and `elapsed_s` measurement."
        ),
    )
    return write_receipts(deck_path, record)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def run_demo(out_dir: Path | str = DEFAULT_OUT_DIR) -> Path:
    """Run the demo end-to-end. Returns the path to the primary .pptx artifact.

    Pipeline:

    1. Resolve / create the output directory.
    2. Copy the bundled sample paper metadata + figures into ``<out>/inputs/``
       so users can inspect (and tweak) the seed data.
    3. Compose a 5-7 slide :class:`vaultlab.slides.deck.DeckPlan`
       deterministically from the bundled metadata.
    4. Render the plan to ``<out>/deck.pptx`` via
       :func:`vaultlab.slides.deck.build_deck`.
    5. Write the standard vaultlab provenance receipts
       (``.provenance.json`` + ``.method.md``) next to the deck.
    """
    t0 = time.time()
    out = Path(out_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    # Step 1: copy bundled inputs into <out>/inputs/ for inspection
    inputs_dir = out / "inputs"
    (inputs_dir / "figures").mkdir(parents=True, exist_ok=True)
    shutil.copy(_bundled_paper_path(), inputs_dir / "paper.json")
    figure_paths: list[Path] = []
    for src in sorted(_bundled_figures_dir().glob("*.png")):
        dst = inputs_dir / "figures" / src.name
        shutil.copy(src, dst)
        figure_paths.append(dst)

    # Step 2: load metadata (from the copied — not the bundled — file so users
    # who later edit inputs/paper.json see their changes reflected on re-run)
    paper = json.loads((inputs_dir / "paper.json").read_text(encoding="utf-8"))

    # Step 3-4: compose plan + render deck
    from vaultlab.slides.deck import build_deck

    plan = _build_plan_from_paper(paper, figure_paths)
    deck_path = out / DECK_FILENAME
    build_deck(plan, deck_path)

    # Step 5: provenance sidecars
    elapsed = time.time() - t0
    _write_demo_provenance(deck_path, paper, figure_paths, elapsed)

    return deck_path


def main(argv: list[str] | None = None) -> int:
    """Entry point for ``vaultlab demo``."""
    parser = argparse.ArgumentParser(
        prog="vaultlab demo",
        description=(
            "Produce a real audit-clean vaultlab artifact from bundled "
            "sample data. Offline; no API keys required."
        ),
    )
    parser.add_argument(
        "--out-dir",
        default=DEFAULT_OUT_DIR,
        help=f"Output directory (default: {DEFAULT_OUT_DIR})",
    )
    args = parser.parse_args(argv)

    t0 = time.time()
    out_path = run_demo(args.out_dir)
    elapsed = time.time() - t0

    print(f"[vaultlab demo] artifact: {out_path}")
    print(f"[vaultlab demo] elapsed:  {elapsed:.1f}s")
    print(
        f"[vaultlab demo] verify provenance: "
        f"{out_path.with_name(out_path.name + '.provenance.json')}"
    )
    print(f"[vaultlab demo] methods narrative: {out_path.with_name(out_path.name + '.method.md')}")
    print(f"[vaultlab demo] inputs:   {out_path.parent / 'inputs'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
