from __future__ import annotations

from dataclasses import dataclass

from vaultlab.projects.figure_plan import SubpanelPlan, SubpanelReadiness
from vaultlab.projects.readiness import evaluate_promotion, scan_provenance_text


@dataclass(frozen=True)
class _Audit:
    value: bool

    def ok(self) -> bool:
        return self.value


def _subpanel(readiness: SubpanelReadiness) -> SubpanelPlan:
    return SubpanelPlan(
        subpanel_id="fig1-a",
        figure_id="Fig1",
        letter="A",
        concept="Synthetic concept A",
        plot_type="heatmap",
        source_result="results/A.csv",
        analysis_script="analysis/A.py",
        plot_script="plots/A.py",
        output_figure="figures/A.png",
        manifest_path="figures/A.coverage.json",
        layout_sidecar_path="figures/A.png.layout.json",
        visual_qa_path="figures/A.visual-qa.json",
        provenance_path="figures/A.method.md",
        panel_slot_id="A",
        claim_id="claim-A",
        supplement_ids=[],
        readiness=readiness,
    )


def test_scan_provenance_text_detects_placeholder_markers_case_insensitively() -> None:
    scan = scan_provenance_text("Autogenerated TODO: <fill this in>; fixme later.")

    assert scan.has_placeholders is True
    assert scan.matched_markers == ["todo", "<fill", "autogenerated", "fixme"]
    assert scan.placeholder_counts["todo"] == 1
    assert scan.placeholder_counts["<fill"] == 1


def test_scan_provenance_text_word_boundaries_avoid_identifier_false_positives() -> None:
    flagged = scan_provenance_text("TODO: fill this in. TBD. XXX.")
    assert "todo" in flagged.matched_markers
    assert "tbd" in flagged.matched_markers
    assert "xxx" in flagged.matched_markers

    # Short markers embedded in longer identifiers must NOT false-positive.
    clean = scan_provenance_text("Rendered with subtbd_v2 and maxxxx settings; todoist export.")
    assert clean.matched_markers == []
    assert clean.has_placeholders is False


def test_evaluate_promotion_blocks_deck_ready_claim_with_placeholder_marker() -> None:
    gate = evaluate_promotion(
        _subpanel(SubpanelReadiness.DECK_READY),
        layout_audit=_Audit(True),
        coverage_audit=_Audit(True),
        provenance_scan=scan_provenance_text("TODO: record what was done."),
        panel_audit=_Audit(True),
    )

    assert gate.passed is False
    assert gate.computed_readiness is SubpanelReadiness.DISPLAY_EXISTS
    assert gate.blockers == [
        "provenance_placeholder: record what was",
        "provenance_placeholder: todo",
    ]
    assert gate.overall_severity == "fail"


def test_evaluate_promotion_reports_exact_blocker_for_each_monotonic_rung() -> None:
    clean_scan = scan_provenance_text("Inputs, parameters, and export path are recorded.")

    coverage_gate = evaluate_promotion(
        _subpanel(SubpanelReadiness.PROVENANCE_VERIFIED),
        layout_audit=_Audit(True),
        coverage_audit=_Audit(False),
        provenance_scan=clean_scan,
        panel_audit=_Audit(True),
    )
    assert coverage_gate.blockers == ["coverage_audit_failed"]
    assert coverage_gate.computed_readiness is SubpanelReadiness.DISPLAY_EXISTS

    layout_gate = evaluate_promotion(
        _subpanel(SubpanelReadiness.GEOMETRY_QA_PASSED),
        layout_audit=_Audit(False),
        coverage_audit=_Audit(True),
        provenance_scan=clean_scan,
        panel_audit=_Audit(True),
    )
    assert layout_gate.blockers == ["layout_audit_failed"]
    assert layout_gate.computed_readiness is SubpanelReadiness.PROVENANCE_VERIFIED

    panel_gate = evaluate_promotion(
        _subpanel(SubpanelReadiness.DECK_READY),
        layout_audit=_Audit(True),
        coverage_audit=_Audit(True),
        provenance_scan=clean_scan,
        panel_audit=_Audit(False),
    )
    assert panel_gate.blockers == ["panel_audit_failed"]
    assert panel_gate.computed_readiness is SubpanelReadiness.GEOMETRY_QA_PASSED

    ready_gate = evaluate_promotion(
        _subpanel(SubpanelReadiness.DECK_READY),
        layout_audit=_Audit(True),
        coverage_audit=_Audit(True),
        provenance_scan=clean_scan,
        panel_audit=_Audit(True),
    )
    assert ready_gate.passed is True
    assert ready_gate.blockers == []
    assert ready_gate.computed_readiness is SubpanelReadiness.DECK_READY


def test_evaluate_promotion_does_not_treat_failed_claim_as_success() -> None:
    gate = evaluate_promotion(
        _subpanel(SubpanelReadiness.FAILED),
        layout_audit=_Audit(True),
        coverage_audit=_Audit(True),
        provenance_scan=scan_provenance_text("Inputs, parameters, and export path are recorded."),
        panel_audit=_Audit(True),
    )

    assert gate.passed is False
    assert gate.computed_readiness is SubpanelReadiness.DECK_READY
    assert gate.blockers == ["requested_readiness_failed"]
