"""Sidecar writers for provenance receipts.

Implements the AGENTS.md mandate: every output drops BOTH a
``<output>.provenance.json`` (machine-readable) and a ``<output>.method.md``
(human-readable narrative) sidecar next to it.

Also maintains an append-only JSONL index (``.vaultlab-provenance.jsonl``) in
the output directory — useful for queries like "all figures generated by
deep-think for finding F001" without scanning every sidecar individually.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any

from ._record import ProvenanceRecord

PROVENANCE_INDEX = ".vaultlab-provenance.jsonl"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def write_receipts(
    output_path: str | os.PathLike[str],
    record: ProvenanceRecord,
    *,
    index_dir: str | os.PathLike[str] | None = None,
) -> tuple[Path, Path]:
    """Write the two sidecar receipts for ``output_path``.

    Per AGENTS.md, every vaultlab output file emits:

    - ``<output_path>.provenance.json`` — machine-readable JSON receipt
    - ``<output_path>.method.md`` — human-readable methods narrative

    Both files are placed next to ``output_path`` (sibling files, same dir).
    The output file itself does **not** need to exist when this is called —
    callers may write the receipts before, during, or after producing the
    output. ``output_path`` is treated purely as a naming anchor.

    The append-only JSONL index at ``<index_dir>/.vaultlab-provenance.jsonl``
    accumulates one line per receipt for cheap "find all outputs matching X"
    queries. When ``index_dir`` is ``None`` it defaults to the directory
    containing ``output_path``.

    Returns
    -------
    (json_path, method_path)
        Paths to the two sidecar files that were written.
    """
    out = Path(output_path)
    json_path = _sidecar_path(out, ".provenance.json")
    method_path = _sidecar_path(out, ".method.md")

    json_path.parent.mkdir(parents=True, exist_ok=True)

    payload = {"output": str(out), **record.to_dict()}
    json_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False),
        encoding="utf-8",
    )

    method_path.write_text(_render_method_markdown(out, record), encoding="utf-8")

    _append_to_index(out, record, index_dir)

    return json_path, method_path


def hash_inputs(paths: list[str | os.PathLike[str]]) -> dict[str, str]:
    """Compute sha256 hashes for a list of input files.

    Convenience for populating ``ProvenanceRecord.input_hashes``. Skips paths
    that don't exist (records ``"<missing>"`` instead of raising) — provenance
    is best-effort metadata, never a hard gate.
    """
    out: dict[str, str] = {}
    for raw in paths:
        p = Path(raw)
        if not p.is_file():
            out[str(p)] = "<missing>"
            continue
        h = hashlib.sha256()
        with p.open("rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
        out[str(p)] = h.hexdigest()
    return out


# ---------------------------------------------------------------------------
# Internal — sidecar paths + index append
# ---------------------------------------------------------------------------


def _sidecar_path(output: Path, suffix: str) -> Path:
    """``foo.png`` → ``foo.png.provenance.json`` (always *append* the suffix)."""
    return output.with_name(output.name + suffix)


def _append_to_index(
    output: Path,
    record: ProvenanceRecord,
    index_dir: str | os.PathLike[str] | None,
) -> Path:
    directory = Path(index_dir) if index_dir is not None else output.parent
    directory.mkdir(parents=True, exist_ok=True)
    index_path = directory / PROVENANCE_INDEX
    entry = {"path": str(output.resolve()), **record.to_dict()}
    with index_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    return index_path


# ---------------------------------------------------------------------------
# Internal — method.md narrative renderer
# ---------------------------------------------------------------------------


def _render_method_markdown(output: Path, record: ProvenanceRecord) -> str:
    """Render a human-readable methods narrative.

    The format is a small superset of what a Methods section in a paper
    expects: title, generation summary, inputs, parameters, related outputs,
    and free-form notes. Any field that's empty is simply omitted — the
    sidecar should never bury the reader in placeholder boilerplate.
    """
    lines: list[str] = []
    title = output.name or "output"
    lines.append(f"# Method — {title}")
    lines.append("")
    lines.append(f"Output file: `{output}`")
    lines.append("")

    lines.append("## Generation")
    lines.append("")
    lines.append(f"- Generated by: `{record.generated_by}`")
    lines.append(f"- Generated at: {record.generated_at}")
    if record.code_version:
        lines.append(f"- Code version: `{record.code_version}`")
    if record.model:
        lines.append(f"- Model: `{record.model}`")
    if record.seed is not None:
        lines.append(f"- Seed: {record.seed}")
    lines.append("")

    if record.project or record.topic or record.investigation_mode or record.meeting_mode \
            or record.round is not None:
        lines.append("## Context")
        lines.append("")
        if record.project:
            lines.append(f"- Project: {record.project}")
        if record.topic:
            lines.append(f"- Topic: {record.topic}")
        if record.investigation_mode:
            lines.append(f"- Investigation mode: {record.investigation_mode}")
        if record.meeting_mode:
            lines.append(f"- Meeting mode: {record.meeting_mode}")
        if record.round is not None:
            lines.append(f"- Round: {record.round}")
        lines.append("")

    if record.inputs or record.input_hashes:
        lines.append("## Inputs")
        lines.append("")
        for inp in record.inputs:
            digest = record.input_hashes.get(inp)
            if digest:
                lines.append(f"- `{inp}` — sha256:{digest[:12]}…")
            else:
                lines.append(f"- `{inp}`")
        # input_hashes entries that weren't in inputs (rare but possible)
        for path, digest in record.input_hashes.items():
            if path not in record.inputs:
                lines.append(f"- `{path}` — sha256:{digest[:12]}…")
        lines.append("")

    if record.params:
        lines.append("## Parameters")
        lines.append("")
        for key, value in record.params.items():
            lines.append(f"- `{key}` = `{_format_param(value)}`")
        lines.append("")

    if record.related_outputs:
        lines.append("## Related outputs")
        lines.append("")
        for ro in record.related_outputs:
            lines.append(f"- `{ro}`")
        lines.append("")

    if record.finding_ids or record.tags or record.kind:
        lines.append("## Classification")
        lines.append("")
        if record.kind:
            lines.append(f"- Kind: {record.kind}")
        if record.finding_ids:
            lines.append(f"- Finding IDs: {', '.join(record.finding_ids)}")
        if record.tags:
            lines.append(f"- Tags: {', '.join(record.tags)}")
        lines.append("")

    if record.notes:
        lines.append("## Notes")
        lines.append("")
        lines.append(record.notes.rstrip())
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _format_param(value: Any) -> str:
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value)


__all__ = [
    "PROVENANCE_INDEX",
    "hash_inputs",
    "write_receipts",
]
