"""Bundled sample data for ``vaultlab demo``.

Contents:

- ``paper.json`` — bibliographic metadata + abstract + key claims for one
  real open-access paper (used as the journal-club deck seed)
- ``figures/`` — synthetic PNGs generated by ``_generate_demo_figures.py``
  (committed so the demo runs without matplotlib on first install)
- ``_generate_demo_figures.py`` — re-run after editing to refresh the PNGs

The demo command lives at :mod:`vaultlab.cli.demo`.
"""
