"""Deterministic readiness ladder for planned figure subpanels."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Literal, cast

from vaultlab.projects.figure_plan import SubpanelPlan, SubpanelReadiness

PLACEHOLDER_MARKERS: tuple[str, ...] = (
    "record what was",
    "todo",
    "<fill",
    "autogenerated",
    "tbd",
    "fixme",
    "xxx",
)

ReadinessSeverity = Literal["pass", "warn", "fail"]

_SEVERITY_RANK: dict[ReadinessSeverity, int] = {"pass": 0, "warn": 1, "fail": 2}


@dataclass(frozen=True)
class ProvenanceScan:
    """String-only scan for placeholder markers in provenance text."""

    matched_markers: list[str]
    placeholder_counts: dict[str, int]
    text_length: int

    @property
    def has_placeholders(self) -> bool:
        """Return True when any placeholder marker was found."""

        return bool(self.matched_markers)

    def to_dict(self) -> dict[str, Any]:
        """Serialize this scan to a JSON-ready dict."""

        return {
            "matched_markers": list(self.matched_markers),
            "placeholder_counts": dict(self.placeholder_counts),
            "text_length": self.text_length,
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> ProvenanceScan:
        """Build a provenance scan from parsed JSON."""

        raw_counts = payload.get("placeholder_counts", {})
        return cls(
            matched_markers=_string_list(payload.get("matched_markers", [])),
            placeholder_counts=(
                {str(key): int(value) for key, value in raw_counts.items()}
                if isinstance(raw_counts, dict)
                else {}
            ),
            text_length=int(payload.get("text_length", 0)),
        )

    def validate(self) -> list[str]:
        """Return soft scan-record problems."""

        problems: list[str] = []
        for marker in self.matched_markers:
            if marker not in PLACEHOLDER_MARKERS:
                problems.append(f"unknown placeholder marker: {marker}")
            if marker not in self.placeholder_counts:
                problems.append(f"missing placeholder count for marker: {marker}")
        if self.text_length < 0:
            problems.append("text_length must be non-negative")
        return problems

    def audit(self) -> ReadinessAudit:
        """Audit the scan record itself, not the promotion decision."""

        return _audit_from_messages(self.validate())


@dataclass(frozen=True)
class PromotionGate:
    """Result of comparing a claimed readiness rung with deterministic evidence."""

    subpanel_id: str
    requested_readiness: SubpanelReadiness
    computed_readiness: SubpanelReadiness
    passed: bool
    blockers: list[str] = field(default_factory=list)
    overall_severity: ReadinessSeverity = "pass"

    def ok(self) -> bool:
        """Return True when the readiness claim is supported."""

        return self.passed

    def to_dict(self) -> dict[str, Any]:
        """Serialize this promotion gate."""

        return {
            "subpanel_id": self.subpanel_id,
            "requested_readiness": self.requested_readiness.value,
            "computed_readiness": self.computed_readiness.value,
            "passed": self.passed,
            "blockers": list(self.blockers),
            "overall_severity": self.overall_severity,
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> PromotionGate:
        """Build a promotion gate from parsed JSON."""

        computed = _readiness_from_value(
            payload.get("computed_readiness"),
            SubpanelReadiness.DISPLAY_EXISTS,
        )
        requested = _readiness_from_value(
            payload.get("requested_readiness"),
            SubpanelReadiness.DISPLAY_EXISTS,
        )
        blockers = _string_list(payload.get("blockers", []))
        passed = bool(payload.get("passed", False))
        return cls(
            subpanel_id=str(payload.get("subpanel_id", "")),
            requested_readiness=requested,
            computed_readiness=computed,
            passed=passed,
            blockers=blockers,
            overall_severity=_severity_from_value(payload.get("overall_severity")),
        )

    def validate(self) -> list[str]:
        """Return soft gate-record problems."""

        problems: list[str] = []
        if not self.subpanel_id.strip():
            problems.append("promotion gate missing subpanel_id")
        if self.passed and self.blockers:
            problems.append("passed promotion gate cannot contain blockers")
        if not self.passed and self.overall_severity != "fail":
            problems.append("failed promotion gate must have fail severity")
        return problems

    def audit(self) -> ReadinessAudit:
        """Audit the gate record itself."""

        return _audit_from_messages(self.validate())


@dataclass(frozen=True)
class ReadinessProblem:
    """One structured readiness audit problem."""

    severity: ReadinessSeverity
    message: str

    def to_dict(self) -> dict[str, str]:
        """Serialize this problem."""

        return {"severity": self.severity, "message": self.message}

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> ReadinessProblem:
        """Build a readiness problem from parsed JSON."""

        return cls(
            severity=_severity_from_value(payload.get("severity")),
            message=str(payload.get("message", "")),
        )


@dataclass(frozen=True)
class ReadinessAudit:
    """Structured result for readiness-record validation."""

    overall_severity: ReadinessSeverity
    problems: list[ReadinessProblem] = field(default_factory=list)

    @property
    def n_fail(self) -> int:
        """Number of failing checks."""

        return sum(1 for problem in self.problems if problem.severity == "fail")

    @property
    def n_warn(self) -> int:
        """Number of warning checks."""

        return sum(1 for problem in self.problems if problem.severity == "warn")

    def ok(self) -> bool:
        """Return True when no failing checks are present."""

        return self.n_fail == 0

    def to_dict(self) -> dict[str, Any]:
        """Serialize this audit."""

        return {
            "overall_severity": self.overall_severity,
            "problems": [problem.to_dict() for problem in self.problems],
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> ReadinessAudit:
        """Build a readiness audit from parsed JSON."""

        problems = [
            ReadinessProblem.from_dict(item) for item in _dict_list(payload.get("problems", []))
        ]
        return cls(overall_severity=_aggregate(problems), problems=problems)


def scan_provenance_text(text: str) -> ProvenanceScan:
    """Scan provenance text for deterministic placeholder markers."""

    normalized = text.lower()
    counts: dict[str, int] = {}
    for marker in PLACEHOLDER_MARKERS:
        count = _count_marker(normalized, marker)
        if count > 0:
            counts[marker] = count
    return ProvenanceScan(
        matched_markers=[marker for marker in PLACEHOLDER_MARKERS if marker in counts],
        placeholder_counts=counts,
        text_length=len(text),
    )


def _count_marker(normalized: str, marker: str) -> int:
    """Count placeholder-marker occurrences in already-lowercased text.

    Word-like markers (alphanumeric at both ends, e.g. ``tbd`` / ``xxx``) are
    counted with word boundaries so they do not false-positive as substrings of
    longer identifiers (``maxxxx``, ``subtbd``). Markers that are not bounded by
    word characters (e.g. ``<fill``) fall back to plain substring counting.
    """

    if marker[:1].isalnum() and marker[-1:].isalnum():
        return len(re.findall(rf"\b{re.escape(marker)}\b", normalized))
    return normalized.count(marker)


def evaluate_promotion(
    subpanel: SubpanelPlan,
    *,
    layout_audit: Any,
    coverage_audit: Any,
    provenance_scan: ProvenanceScan,
    panel_audit: Any,
) -> PromotionGate:
    """Evaluate a subpanel's claimed readiness against monotonic QA rungs."""

    blockers: list[str] = []
    requested = subpanel.readiness
    computed = SubpanelReadiness.DISPLAY_EXISTS

    if not subpanel.output_figure.strip():
        computed = SubpanelReadiness.FAILED
        if requested.rank >= SubpanelReadiness.DISPLAY_EXISTS.rank:
            blockers.append("missing_output_figure")
        return _gate(subpanel.subpanel_id, requested, computed, blockers)

    provenance_blockers = _provenance_blockers(provenance_scan)
    if not _audit_ok(coverage_audit):
        provenance_blockers.append("coverage_audit_failed")
    if provenance_blockers:
        if requested.rank >= SubpanelReadiness.PROVENANCE_VERIFIED.rank:
            blockers.extend(provenance_blockers)
        return _gate(subpanel.subpanel_id, requested, computed, blockers)
    computed = SubpanelReadiness.PROVENANCE_VERIFIED

    if not _audit_ok(layout_audit):
        if requested.rank >= SubpanelReadiness.GEOMETRY_QA_PASSED.rank:
            blockers.append("layout_audit_failed")
        return _gate(subpanel.subpanel_id, requested, computed, blockers)
    computed = SubpanelReadiness.GEOMETRY_QA_PASSED

    if panel_audit is None:
        if requested.rank >= SubpanelReadiness.DECK_READY.rank:
            blockers.append("panel_audit_missing")
        return _gate(subpanel.subpanel_id, requested, computed, blockers)
    if not _audit_ok(panel_audit):
        if requested.rank >= SubpanelReadiness.DECK_READY.rank:
            blockers.append("panel_audit_failed")
        return _gate(subpanel.subpanel_id, requested, computed, blockers)
    computed = SubpanelReadiness.DECK_READY

    return _gate(subpanel.subpanel_id, requested, computed, blockers)


def _gate(
    subpanel_id: str,
    requested: SubpanelReadiness,
    computed: SubpanelReadiness,
    blockers: list[str],
) -> PromotionGate:
    if requested is SubpanelReadiness.FAILED:
        blockers = list(blockers)
        if "requested_readiness_failed" not in blockers:
            blockers.append("requested_readiness_failed")
        return PromotionGate(
            subpanel_id=subpanel_id,
            requested_readiness=requested,
            computed_readiness=computed,
            passed=False,
            blockers=blockers,
            overall_severity="fail",
        )

    passed = computed is not SubpanelReadiness.FAILED and computed.rank >= requested.rank
    severity: ReadinessSeverity = "pass" if passed else "fail"
    return PromotionGate(
        subpanel_id=subpanel_id,
        requested_readiness=requested,
        computed_readiness=computed,
        passed=passed,
        blockers=list(blockers),
        overall_severity=severity,
    )


def _provenance_blockers(scan: ProvenanceScan) -> list[str]:
    blockers = [f"provenance_placeholder: {marker}" for marker in scan.matched_markers]
    if scan.text_length == 0:
        blockers.append("provenance_empty")
    return blockers


def _audit_ok(audit: Any) -> bool:
    if audit is None:
        return False
    ok_attr = getattr(audit, "ok", None)
    if callable(ok_attr):
        return bool(ok_attr())
    if isinstance(ok_attr, bool):
        return ok_attr
    return False


def _audit_from_messages(messages: list[str]) -> ReadinessAudit:
    problems = [ReadinessProblem("fail", message) for message in messages]
    return ReadinessAudit(overall_severity=_aggregate(problems), problems=problems)


def _aggregate(problems: list[ReadinessProblem]) -> ReadinessSeverity:
    if not problems:
        return "pass"
    return max((problem.severity for problem in problems), key=lambda severity: _SEVERITY_RANK[severity])


def _severity_from_value(value: Any) -> ReadinessSeverity:
    if value in {"pass", "warn", "fail"}:
        return cast("ReadinessSeverity", value)
    return "fail"


def _readiness_from_value(value: Any, default: SubpanelReadiness) -> SubpanelReadiness:
    if value is None:
        return default
    for member in SubpanelReadiness:
        if value == member.value or value == member.name:
            return member
    return default


def _string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item) for item in value]


def _dict_list(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [cast("dict[str, Any]", item) for item in value if isinstance(item, dict)]


__all__ = [
    "PLACEHOLDER_MARKERS",
    "PromotionGate",
    "ProvenanceScan",
    "ReadinessAudit",
    "ReadinessProblem",
    "ReadinessSeverity",
    "evaluate_promotion",
    "scan_provenance_text",
]
