"""Figure-understanding prototype — annotate CAR-T figures + build review PPTX.

Bobby's 2026-04-29 ask: prove VaultLab can understand published-style figures.
For each figure, identify discrete elements + their approximate locations,
draw labeled callouts directly on the image (bounding boxes + leader lines +
text), then build a PowerPoint where each slide shows one annotated figure
with full speaker notes.

The annotation data here was generated by Claude reading each figure visually
(this is the understanding being demonstrated). In a real vaultlab.figures.understand
build, this would come from the runner with a vision-grounded role.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Tuple

from PIL import Image, ImageDraw, ImageFont
from pptx import Presentation
from pptx.util import Emu, Inches, Pt
from pptx.dml.color import RGBColor

INPUT_DIR = Path(r"C:\tmp\cart_figs_v13")
OUTPUT_DIR = Path(r"C:\tmp\cart_figs_v13_annotated")
OUTPUT_DIR.mkdir(exist_ok=True)
PPTX_OUT = Path(r"C:\Users\bobby\Downloads\car_t_decks\figure_understanding_demo.pptx")


# ---------------------------------------------------------------------------
# Annotation data — Bobby will judge these against the actual figure content.
# Coordinates are fractional [0,1] of (width, height). Each (x, y, w, h) defines
# the bounding box vaultlab thinks contains the labeled element. The label is
# the short on-figure callout; explanation goes into speaker notes.
# ---------------------------------------------------------------------------


@dataclass
class Annotation:
    label: str              # short text drawn on the figure
    bbox: Tuple[float, float, float, float]  # (x, y, w, h) in [0,1]
    explanation: str        # for speaker notes


@dataclass
class FigurePlan:
    image_filename: str
    title: str
    overall_caption: str
    long_explanation: str   # paragraph for speaker notes
    annotations: list[Annotation]


PLANS: list[FigurePlan] = [
    FigurePlan(
        image_filename="image1.png",
        title="Mechanisms of Antigen Recognition in Adoptive T Cell Therapy",
        overall_caption=(
            "Three-panel comparison (BioRender, VanNoy 2025) of how engineered T cells "
            "recognize tumor antigens: (a) endogenous + introduced TCR via MHC class I, "
            "(b) tumor-associated antigen (TAA) via aberrant protein presentation through MHC, "
            "(c) MHC-independent CAR recognition via scFv binding directly to surface antigen."
        ),
        long_explanation=(
            "Panel (a) — TCR therapy: the natural TCR signaling architecture is preserved. "
            "The introduced TCR (green dimer) binds peptide presented on MHC class I (gray "
            "with red peptide dot). CD3 chains (orange) and ζ-chains transduce the signal. "
            "Endogenous TCR (blue) competes for the same MHC-peptide complex.\n\n"
            "Panel (b) — TAA therapy: an aberrantly expressed self-protein (red bar at top) is "
            "presented via MHC class I. The endogenous TCR is the receptor here — no exogenous "
            "construct required, but the antigen must be both tumor-restricted and "
            "MHC-presentable. CD3+ζ chains again handle the downstream signaling.\n\n"
            "Panel (c) — CAR T: the chimeric antigen receptor (red top = antigen recognition "
            "domain, yellow oval annotated 'MHC Independent', green/orange = intracellular "
            "signaling domains) binds the surface antigen directly via its scFv. No MHC "
            "presentation required, broadening the addressable antigen set but also exposing "
            "the construct to MHC-independent off-target hits."
        ),
        annotations=[
            Annotation("Endogenous TCR", (0.05, 0.45, 0.10, 0.30),
                       "Native TCR (blue dimer) binds same MHC-peptide as introduced TCR — competes for ligand."),
            Annotation("Introduced TCR", (0.18, 0.40, 0.10, 0.30),
                       "Engineered TCR (green) is the therapeutic receptor in TCR therapy."),
            Annotation("MHC-I + peptide", (0.20, 0.30, 0.08, 0.10),
                       "MHC class I (gray) presenting tumor peptide (red dot)."),
            Annotation("CD3 / ζ chains", (0.10, 0.65, 0.20, 0.20),
                       "Signal-transduction subunits — orange = CD3 ε/γ/δ; tail = ζ chains with ITAMs."),
            Annotation("TAA presented", (0.42, 0.30, 0.08, 0.20),
                       "Aberrantly expressed self-protein presented via MHC-I as neoantigen."),
            Annotation("scFv (Antigen Recognition)", (0.72, 0.42, 0.10, 0.18),
                       "Single-chain variable fragment binds surface antigen directly. "
                       "Marked 'MHC Independent' on the figure."),
            Annotation("CAR signaling domains", (0.78, 0.65, 0.10, 0.20),
                       "Co-stimulatory (green) + activation (orange) domains. CD28/4-1BB + CD3-ζ-style ITAMs."),
        ],
    ),
    FigurePlan(
        image_filename="image2.png",
        title="Five Generations of CAR Design",
        overall_caption=(
            "Architectural evolution from native TCR through 1st–5th generation CARs. "
            "Each row in the structure shows progressive additions of co-stimulatory + "
            "cytokine-inducer domains."
        ),
        long_explanation=(
            "The TCR (left) is shown for reference: αβ heterodimer + CD3γε/δε + ζ chains, "
            "ZAP70 in the cytoplasm.\n\n"
            "1st gen CAR: scFv ectodomain -> hinge -> transmembrane -> CD3ζ alone. Limited "
            "persistence + cytokine production.\n\n"
            "2nd gen: adds ONE co-stimulatory domain (CD28 or 4-1BB) — the breakthrough "
            "FDA-approved generation.\n\n"
            "3rd gen: adds a SECOND co-stimulatory domain (e.g., CD28 + 4-1BB), aiming for "
            "richer signaling.\n\n"
            "4th gen ('TRUCK'): adds a cytokine-inducer module — engineered to release "
            "cytokines (IL-12, etc.) on antigen recognition for TME modulation.\n\n"
            "5th gen: adds a JAK-STAT activation domain (cytokine-inducer recruiter), "
            "letting the CAR drive STAT3/5 signaling directly. Visible in the figure as "
            "the blue/orange element labeled JAK + STAT3/5."
        ),
        annotations=[
            Annotation("TCR (reference)", (0.04, 0.10, 0.13, 0.50),
                       "Native TCR architecture: αβ chains + CD3γε/δε + ζ chains + ZAP70."),
            Annotation("1st gen CAR (CD3ζ only)", (0.20, 0.10, 0.13, 0.80),
                       "First-generation: scFv -> CD3ζ. Poor persistence; superseded clinically."),
            Annotation("2nd gen (+1 co-stim)", (0.36, 0.10, 0.13, 0.80),
                       "Adds CD28 OR 4-1BB. The clinically dominant generation (axi-cel, tisa-cel, etc.)."),
            Annotation("3rd gen (+2 co-stim)", (0.52, 0.10, 0.13, 0.80),
                       "Two co-stimulatory domains in tandem (CD28 + 4-1BB)."),
            Annotation("4th gen (TRUCK)", (0.66, 0.10, 0.13, 0.80),
                       "Cytokine-inducer module — releases cytokines on antigen engagement."),
            Annotation("5th gen (JAK-STAT)", (0.80, 0.10, 0.16, 0.80),
                       "JAK-binding domain + STAT3/5 activation. Drives cytokine signaling directly."),
            Annotation("Ectodomain band", (0.18, 0.04, 0.78, 0.20),
                       "Above the membrane — antigen-binding domains."),
            Annotation("Endodomain band", (0.18, 0.55, 0.78, 0.40),
                       "Below the membrane — signaling cascade."),
        ],
    ),
    FigurePlan(
        image_filename="image3.png",
        title="Three Signals Required for T-cell Activation",
        overall_caption=(
            "T-cell full activation requires three sequential signals: (a) TCR/CAR engagement, "
            "(b) co-stimulation, (c) cytokine signaling. Each contributes to the effector-function "
            "transcriptional program."
        ),
        long_explanation=(
            "Signal 1 — antigen recognition: TAA (red) bound by CAR (scFv = blue antigen-recognition "
            "domain -> CD3ζ activation -> NFAT cytoplasmic-to-nuclear translocation -> effector-gene "
            "transcription. Without a co-stim signal, this leads to anergy.\n\n"
            "Signal 2 — co-stimulation: a second receptor (CD28 / 4-1BB / OX40, etc.) engages its "
            "ligand. Drives PI3K/AKT, NF-κB, MAPK pathways. The figure shows this as the green arrow "
            "into the nucleus alongside NFAT, jointly licensing 'Effector Function'.\n\n"
            "Signal 3 — cytokines: IL-2 family cytokines (IL-2, IL-7, IL-15, IL-21) drive proliferation, "
            "differentiation, and persistence. Released into the local milieu (the dot field around the "
            "third T cell) and trigger JAK-STAT signaling. Without Signal 3, effector cells fail to "
            "expand and persist."
        ),
        annotations=[
            Annotation("Signal 1: TAA + CAR", (0.10, 0.05, 0.25, 0.30),
                       "TAA (red) -> CAR scFv binding -> primary activation."),
            Annotation("CAR architecture", (0.08, 0.18, 0.18, 0.50),
                       "CD3ζ tail -> NFAT activation -> DNA. Blue = recognition; orange = activation domain."),
            Annotation("Signal 2: co-stim", (0.36, 0.05, 0.25, 0.30),
                       "Second receptor engages ligand. Drives PI3K/AKT, NF-κB, MAPK."),
            Annotation("PI3K/AKT, NF-κB, MAPK", (0.42, 0.30, 0.15, 0.15),
                       "Co-stim downstream pathways shown in green text — converge on the nucleus."),
            Annotation("Signal 3: cytokines", (0.65, 0.05, 0.30, 0.40),
                       "Cytokine release (blue dots) — IL-2 family for proliferation + persistence."),
            Annotation("Effector Function (DNA)", (0.30, 0.65, 0.45, 0.18),
                       "Joint output — transcription of effector cytokines + cytotoxic granules."),
        ],
    ),
    FigurePlan(
        image_filename="image7.png",
        title="CAR-Macrophage (CAR-M) Mechanisms in Solid Tumors",
        overall_caption=(
            "Six-panel overview of how CAR-engineered macrophages attack solid tumors: "
            "antigen-dependent cytotoxicity, TME remodeling, tumor phagocytosis, transcription-"
            "factor activation, infiltration, and a legend of cell-type icons."
        ),
        long_explanation=(
            "Panel A — Antigen-dependent cytotoxicity: CAR-M binds tumor cell, polarizes to M1, "
            "releases IFN-γ + IPS, then secretes activating cytokines (IFN-γ, IL-1β, GM-CSF) "
            "and presents surface protein (CD86, CD14, IL-1R, MHC-II) and inflammatory cytokines "
            "(IL-6, IL-8, IL-12, TNF-α, TNF-β).\n\n"
            "Panel B — TME remodeling and T-cell recruitment: M1 polarization recruits NK cells, "
            "neutrophils, and additional T cells via secreted chemokines.\n\n"
            "Panel C — Tumor phagocytosis: a 3-step pictogram — recognition -> activation/engulfment "
            "-> digestion/elimination. The defining CAR-M effector pathway.\n\n"
            "Panel D — Transcription factor activation causing cytokine release: NF-κB, STAT1, "
            "STAT5, IRF3, IRF5, HIF-1α drive transcription of TLR4, TLR9, CD86, CD80 + downstream "
            "TNF-α, IL-1α, IL-1β, IL-6, IL-12, IL-23 + chemokines (CXCL9–11, CXCL16, CCL5).\n\n"
            "Panel E — Infiltration of CAR-M in solid tumor: schematic showing CAR-Ms penetrating "
            "the tumor mass — macrophages are intrinsically tissue-infiltrating, an advantage over CAR-T "
            "in solid tumors.\n\n"
            "Panel F — Legend: M0 macrophage, M1 macrophage, CAR-M, NK cell, neutrophil, eosinophil, "
            "exhausted CD8+ T cell, activation of exhausted CD8+ T cell, dendritic cell, tumor cell."
        ),
        annotations=[
            Annotation("A: Antigen-dependent cytotoxicity", (0.02, 0.02, 0.55, 0.30),
                       "M0 -> M1 polarization driven by IFN-γ + IPS; releases inflammatory cytokines."),
            Annotation("B: TME remodeling + recruitment", (0.58, 0.02, 0.40, 0.25),
                       "M1 macrophages recruit NK cells, neutrophils, T cells via chemokines."),
            Annotation("C: Tumor phagocytosis (3 steps)", (0.02, 0.34, 0.55, 0.22),
                       "Recognition -> activation/engulfment -> digestion/elimination. Core CAR-M effector pathway."),
            Annotation("D: Transcription-factor activation", (0.02, 0.58, 0.55, 0.35),
                       "NF-κB, STAT1/5, IRF3/5, HIF-1α drive cytokine + chemokine transcription."),
            Annotation("E: Infiltration in solid tumor", (0.58, 0.30, 0.40, 0.25),
                       "CAR-Ms penetrating tumor mass — macrophages cross stromal barriers better than T cells."),
            Annotation("F: Legend (cell types)", (0.58, 0.58, 0.40, 0.40),
                       "Cell-type icon glossary used throughout the panel set."),
            Annotation("Cytokine cocktail (panel A)", (0.30, 0.10, 0.27, 0.22),
                       "IFN-γ, IL-1β, GM-CSF, IL-6, IL-8, IL-12, TNF-α/β — broad inflammatory milieu."),
        ],
    ),
    FigurePlan(
        image_filename="image8.png",
        title="The Cancer-Immunity Cycle (7 Steps)",
        overall_caption=(
            "Chen & Mellman-style 7-step cancer-immunity cycle showing the iterative loop: "
            "antigen release -> presentation -> T-cell priming -> trafficking -> infiltration -> "
            "tumor recognition -> tumor-cell death."
        ),
        long_explanation=(
            "Step 1 — Release of antigens from tumor cells: immunogenic vs tolerogenic cell "
            "death determines downstream priming.\n\n"
            "Step 2 — Tumor antigen presentation: TNF-α, IL-1, IFN-α, CD40, CD40L, ATP, TLR ligands, "
            "IL-10, IL-4, IL-13 — cytokine context shapes DC maturation.\n\n"
            "Step 3 — Priming and activation: CD28/B7.1, CTLA-4/B7.1, CD137/CD137L, OX40/OX40L, "
            "PD-L1/B7.1, PD-L1/PD-1, CD27/CD70, IL-2, prostaglandins.\n\n"
            "Step 4 — Migration of T lymphocytes to tumors: CX3CL1, CXCL9, CXCL10, CCL5 chemokines.\n\n"
            "Step 5 — Infiltration of T lymphocytes in tumors: LFA-1/ICAM-1, selectins, VEGF, "
            "endothelial B receptor (vascular adhesion).\n\n"
            "Step 6 — Recognition of tumor cells by T lymphocytes: TCR engagement, pMHC reduction "
            "in tumor cells (immune escape mechanism).\n\n"
            "Step 7 — Tumor cell death: T lymphocyte granule content (perforin, granzymes), "
            "IFN-γ, plus inhibitory checkpoints — PD-L1/PD-1, PD-L1/B7.1, LAG-3, arginase, MICA/MICB, "
            "TIM-3/phospholipids, TGF-β, B7-H4. Each inhibitor is a therapeutic checkpoint target."
        ),
        annotations=[
            Annotation("1. Release of antigens", (0.05, 0.65, 0.25, 0.25),
                       "Immunogenic vs tolerogenic cell death — defines downstream cycle entry."),
            Annotation("2. Tumor antigen presentation", (0.02, 0.30, 0.20, 0.35),
                       "DCs take up antigens, mature in cytokine context, present on MHC."),
            Annotation("3. Priming + activation", (0.22, 0.05, 0.30, 0.20),
                       "DC + T-cell synapse with co-stimulation + checkpoint signals."),
            Annotation("4. T-cell migration", (0.62, 0.02, 0.30, 0.22),
                       "Chemokine-driven trafficking to tumor: CX3CL1, CXCL9/10, CCL5."),
            Annotation("5. Infiltration", (0.70, 0.25, 0.28, 0.18),
                       "Vascular adhesion: LFA-1/ICAM-1, selectins, VEGF, endothelial B receptor."),
            Annotation("6. Tumor recognition", (0.65, 0.45, 0.30, 0.20),
                       "TCR engages pMHC on tumor cell — but tumors downregulate MHC for escape."),
            Annotation("7. Tumor cell death", (0.30, 0.65, 0.45, 0.25),
                       "Cytotoxic killing modulated by checkpoints: PD-1/L1, LAG-3, TIM-3, TGF-β."),
        ],
    ),
    FigurePlan(
        image_filename="image10.png",
        title="Tumor Microenvironment — Suppressive Mechanisms Against CAR-T",
        overall_caption=(
            "Schematic of multiple converging suppressive forces in the TME that degrade CAR-T "
            "function: suppressive cells, soluble inhibitors, antigen heterogeneity, dysregulated "
            "vasculature, physical barriers."
        ),
        long_explanation=(
            "The central tumor mass is surrounded by labeled suppressive mechanisms:\n\n"
            "Suppressive cells (top-left bubble): MDSCs, Tregs, TAMs target CAR-T directly via "
            "checkpoint engagement. The smaller PD-1/PD-L1 + CTLA-4/CD86 callout shows DC—cancer-cell "
            "interaction with checkpoint engagement.\n\n"
            "Soluble inhibitors (top-right): IL-10, TGF-β, chemokines secreted by MDSCs/Tregs "
            "diffusing through the TME. The blocked-arrow icon indicates these are inhibitory.\n\n"
            "Tumor antigen heterogeneity (right): different tumor cells express different antigens — "
            "the patchwork of red dots vs other markers — so a single-target CAR loses efficacy as "
            "antigen-negative variants escape.\n\n"
            "Dysregulated vasculature (bottom-left): VCAM-1/ICAM-1 down arrow indicates reduced "
            "T-cell extravasation. Tortuous vessel architecture impedes infiltration.\n\n"
            "Physical barriers (bottom-right): ECM (extracellular matrix), CAF (cancer-associated "
            "fibroblasts), high IFP (interstitial fluid pressure) physically exclude T cells.\n\n"
            "Center: O₂, pH, nutrients all DOWN; toxic metabolites (lactate, adenosine) UP — the "
            "metabolic 'shield' around the tumor that further suppresses T-cell function."
        ),
        annotations=[
            Annotation("Suppressive cells: MDSC, Treg, TAM", (0.10, 0.05, 0.30, 0.25),
                       "MDSCs / Tregs / TAMs engage CAR-T via inhibitory ligands; suppress directly."),
            Annotation("Checkpoint detail (PD-1, CTLA-4)", (0.05, 0.30, 0.20, 0.25),
                       "DC-cancer-cell interaction. PD-1/PD-L1 + CTLA-4/CD86 — therapeutic checkpoint targets."),
            Annotation("Soluble inhibitors: IL-10, TGF-β", (0.70, 0.10, 0.25, 0.20),
                       "Cytokines + chemokines diffusing from MDSCs/Tregs — inhibitory milieu."),
            Annotation("Tumor antigen heterogeneity", (0.65, 0.30, 0.30, 0.30),
                       "Different antigen profiles per tumor subclone -> single-CAR escape."),
            Annotation("Metabolic suppression", (0.36, 0.40, 0.25, 0.18),
                       "O₂/pH/nutrients DOWN, toxic metabolites (lactate, adenosine) UP."),
            Annotation("Dysregulated vasculature", (0.05, 0.62, 0.35, 0.18),
                       "VCAM-1/ICAM-1 down — reduced T-cell extravasation."),
            Annotation("Physical barriers: ECM, CAF, IFP", (0.55, 0.65, 0.40, 0.30),
                       "Stromal exclusion of T cells: dense ECM + CAFs + high interstitial pressure."),
        ],
    ),
    FigurePlan(
        image_filename="image13.png",
        title="CAR-T / CAR-NK / CAR-M Interactions in the Tumor Microenvironment",
        overall_caption=(
            "Comparative diagram showing how three engineered cell types (CAR-T, CAR-NK, CAR-M) "
            "kill cancer cells in the TME. Top legend identifies all immune cell types in the "
            "left-side panel."
        ),
        long_explanation=(
            "Top legend identifies 11 cell types: B cell, Cancer cell, CAR-T cell, CAR-NK cell, "
            "CAR-M cell, Dendritic cell, Fibroblast, Macrophage, MDSC, Neutrophil, NK cell, T cell, "
            "Treg cell. These appear as recurring icons throughout the figure.\n\n"
            "Panel A (Tumor Microenvironment): heterogeneous mix of all listed cells around tumor "
            "(red). Two cytokine pools labeled at bottom — stimulatory (TNF, IL-1, IL-6, IL-12, "
            "IL-18 in blue) vs inhibitory (TGF-β, IL-4, IL-10 in red) — set the polarization "
            "balance.\n\n"
            "Panel B (interaction comparisons, three rows):\n"
            "Row 1 — CAR-T cell + cancer cell -> granzymes + perforin -> death of cancer cells. "
            "Classical cytotoxic granule mechanism.\n"
            "Row 2 — CAR-NK cell + cancer cell -> perforin -> death of cancer cells. NK cells "
            "lack the same granzyme palette but retain perforin-mediated lysis. Less GVHD risk = "
            "off-the-shelf potential.\n"
            "Row 3 — CAR-M cell + cancer cell -> proinflammatory + anti-inflammatory cytokines -> "
            "death of cancer cells. Distinct mechanism: tumor inflammation + reprogramming + "
            "phagocytosis (vs direct lysis)."
        ),
        annotations=[
            Annotation("Cell-type legend (11 icons)", (0.02, 0.02, 0.96, 0.10),
                       "Glossary: B, Cancer, CAR-T/NK/M, DC, Fibroblast, Macrophage, MDSC, Neutrophil, NK, T, Treg."),
            Annotation("A: Tumor microenvironment", (0.02, 0.15, 0.45, 0.55),
                       "Heterogeneous TME with all listed cell types. Cytokine balance bottom-labeled."),
            Annotation("Stimulatory vs inhibitory cytokines", (0.10, 0.78, 0.30, 0.20),
                       "Blue = TNF, IL-1/6/12/18 (stimulatory); Red = TGF-β, IL-4/10 (inhibitory)."),
            Annotation("CAR-T -> granzymes + perforin", (0.50, 0.15, 0.45, 0.20),
                       "Classical cytotoxic-granule killing — primary CAR-T mechanism."),
            Annotation("CAR-NK -> perforin", (0.50, 0.40, 0.45, 0.20),
                       "Perforin-mediated lysis. Off-the-shelf potential (less GVHD risk)."),
            Annotation("CAR-M -> cytokines", (0.50, 0.65, 0.45, 0.30),
                       "Pro+anti-inflammatory cytokines + phagocytosis. Distinct from direct lysis."),
        ],
    ),
    FigurePlan(
        image_filename="image14.png",
        title="Notch Receptor + syn-Notch CAR-T Architecture",
        overall_caption=(
            "Two-panel figure: (A) native Notch receptor domain architecture, (B) syn-Notch "
            "CAR-T system using Notch-style heterodimerization for antigen-priming gated CAR "
            "expression."
        ),
        long_explanation=(
            "Panel A — Native Notch receptor architecture, top-to-bottom:\n"
            "NECD (Notch ExtraCellular Domain): EGF Repeats (yellow stripes) + NRR (Negative "
            "Regulatory Region) containing LNR (Lin-Notch Repeats) + HD (Heterodimerization Domain).\n"
            "TM (Transmembrane): single-pass.\n"
            "NICD (Notch IntraCellular Domain): RAM domain -> ANK (Ankyrin repeats) -> NLS (Nuclear "
            "Localization Signal) -> PEST (degradation signal).\n\n"
            "Panel B — syn-Notch CAR-T system (5-step):\n"
            "(1) Recognition Domain on the syn-Notch receptor binds first antigen on target cell.\n"
            "(2) Conformational change -> ADAM proteolytic cleavage -> γ-secretase cleavage releases "
            "TF (transcription factor) into cytoplasm.\n"
            "(3) TF translocates to nucleus -> drives transcription of CAR construct from "
            "engineered locus.\n"
            "(4) Newly translated CAR appears on cell surface; binds second antigen on target "
            "cell — only target cells expressing BOTH antigens trigger killing.\n"
            "(5) Exocytosis of granzyme + perforin -> target cell death.\n\n"
            "Why it matters: syn-Notch enables AND-gate logic. CAR is only induced when antigen #1 "
            "is recognized, then activates only when antigen #2 is present. Reduces on-target/"
            "off-tumor toxicity."
        ),
        annotations=[
            Annotation("EGF Repeats (NECD)", (0.10, 0.04, 0.20, 0.18),
                       "Multiple Epidermal Growth Factor-like repeats — ligand-binding extracellular region."),
            Annotation("NRR: LNR + HD", (0.30, 0.18, 0.20, 0.10),
                       "Negative Regulatory Region — Lin-Notch Repeats + Heterodimerization Domain. "
                       "Holds receptor inactive until ligand binding."),
            Annotation("Transmembrane (TM)", (0.45, 0.27, 0.10, 0.05),
                       "Single-pass transmembrane domain."),
            Annotation("NICD: RAM, ANK, NLS, PEST", (0.30, 0.30, 0.30, 0.15),
                       "Intracellular signaling cassette — RAM-CSL binding, Ankyrin repeats, NLS, PEST degron."),
            Annotation("(1) First antigen binding", (0.05, 0.55, 0.20, 0.10),
                       "syn-Notch recognition domain engages antigen #1."),
            Annotation("(2) ADAM + γ-secretase cleavage", (0.05, 0.70, 0.30, 0.10),
                       "Proteolytic release of synthetic TF into cytoplasm."),
            Annotation("(3) TF -> nucleus -> CAR transcription", (0.30, 0.85, 0.30, 0.10),
                       "TF drives CAR expression from engineered locus — INDUCED, not constitutive."),
            Annotation("(4) Second-antigen recognition", (0.55, 0.55, 0.20, 0.15),
                       "AND-gate: CAR (only present after step 3) binds antigen #2."),
            Annotation("(5) Cytotoxic granule release", (0.78, 0.55, 0.18, 0.30),
                       "Granzyme + perforin exocytosis -> target killing."),
        ],
    ),
]


# ---------------------------------------------------------------------------
# Annotation rendering
# ---------------------------------------------------------------------------


COLORS = [
    (0, 102, 204),    # cobalt
    (220, 50, 47),    # solarized red
    (38, 139, 210),   # blue
    (181, 137, 0),    # solarized yellow
    (133, 153, 0),    # green
    (108, 113, 196),  # violet
    (203, 75, 22),    # orange
    (211, 54, 130),   # magenta
    (42, 161, 152),   # cyan
]


def _font(size: int) -> ImageFont.FreeTypeFont:
    """Best-effort font lookup; falls back to default if Arial unavailable."""
    candidates = [
        r"C:\Windows\Fonts\arialbd.ttf",
        r"C:\Windows\Fonts\arial.ttf",
        "/Library/Fonts/Arial Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVu-Sans-Bold.ttf",
    ]
    for c in candidates:
        if os.path.exists(c):
            return ImageFont.truetype(c, size)
    return ImageFont.load_default()


def annotate_figure(plan: FigurePlan) -> Path:
    """Draw annotations on the figure; save under OUTPUT_DIR; return path."""
    src = INPUT_DIR / plan.image_filename
    img = Image.open(src).convert("RGB")
    W, H = img.size

    # Add 380px right gutter for callout text + leader lines
    GUTTER = 420
    canvas = Image.new("RGB", (W + GUTTER, H), (255, 255, 255))
    canvas.paste(img, (0, 0))
    draw = ImageDraw.Draw(canvas)

    label_font = _font(max(12, H // 60))
    body_font = _font(max(11, H // 75))

    # Place callouts down the right gutter
    n = len(plan.annotations)
    gutter_x = W + 12
    callout_top = 30
    callout_bottom = H - 30
    spacing = (callout_bottom - callout_top) / max(n, 1)

    for i, ann in enumerate(plan.annotations):
        color = COLORS[i % len(COLORS)]
        x, y, w, h = ann.bbox
        bx, by = int(x * W), int(y * H)
        bw, bh = int(w * W), int(h * H)

        # Bounding box on the figure
        draw.rectangle([(bx, by), (bx + bw, by + bh)], outline=color, width=4)

        # Numbered marker in the corner of the box
        num = str(i + 1)
        marker_size = max(28, H // 35)
        marker_xy = (bx, by - marker_size)
        draw.rectangle(
            [marker_xy, (marker_xy[0] + marker_size, marker_xy[1] + marker_size)],
            fill=color,
        )
        # Center the number in the marker
        try:
            tw, th = draw.textbbox((0, 0), num, font=label_font)[2:]
        except AttributeError:
            tw, th = label_font.getsize(num)  # type: ignore[attr-defined]
        draw.text(
            (marker_xy[0] + (marker_size - tw) / 2, marker_xy[1] + (marker_size - th) / 2 - 2),
            num, fill=(255, 255, 255), font=label_font,
        )

        # Callout in the right gutter, vertically distributed
        callout_y = int(callout_top + spacing * i)
        # Leader line from box right-edge to callout
        anchor_box = (bx + bw, by + bh // 2)
        anchor_callout = (gutter_x, callout_y + 8)
        draw.line([anchor_box, anchor_callout], fill=color, width=2)

        # Callout marker
        draw.rectangle(
            [(gutter_x - marker_size - 4, callout_y),
             (gutter_x - 4, callout_y + marker_size)],
            fill=color,
        )
        draw.text(
            (gutter_x - marker_size - 4 + (marker_size - tw) / 2,
             callout_y + (marker_size - th) / 2 - 2),
            num, fill=(255, 255, 255), font=label_font,
        )

        # Wrap label text into ~30-char lines
        wrapped = _wrap(ann.label, max_chars=34)
        for j, line in enumerate(wrapped):
            draw.text(
                (gutter_x + 2, callout_y + j * (max(11, H // 75) + 2)),
                line, fill=(20, 20, 20), font=body_font,
            )

    out = OUTPUT_DIR / f"annotated_{plan.image_filename}"
    canvas.save(out)
    return out


def _wrap(text: str, max_chars: int) -> list[str]:
    words = text.split()
    out: list[str] = []
    cur: list[str] = []
    cur_len = 0
    for w in words:
        if cur_len + len(w) + 1 > max_chars and cur:
            out.append(" ".join(cur))
            cur = [w]
            cur_len = len(w)
        else:
            cur.append(w)
            cur_len += len(w) + 1
    if cur:
        out.append(" ".join(cur))
    return out


# ---------------------------------------------------------------------------
# PPTX assembly
# ---------------------------------------------------------------------------


def build_pptx(plans: list[FigurePlan], annotated_paths: list[Path]) -> Path:
    pres = Presentation()
    pres.slide_width = Inches(13.333)
    pres.slide_height = Inches(7.5)
    blank = pres.slide_layouts[6]

    # Title slide
    s = pres.slides.add_slide(blank)
    title_box = s.shapes.add_textbox(
        Inches(0.5), Inches(2.0), Inches(12.3), Inches(2.0)
    )
    tf = title_box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = "VaultLab Figure-Understanding Demo"
    run.font.name = "Arial"
    run.font.size = Pt(40)
    run.font.bold = True
    run.font.color.rgb = RGBColor(20, 20, 20)

    sub = s.shapes.add_textbox(
        Inches(0.5), Inches(4.2), Inches(12.3), Inches(2.5)
    )
    sf = sub.text_frame
    sf.word_wrap = True
    sub_text = (
        "Source: car_t_30min_v13.pptx — 8 figures from your CAR-T review deck.\n\n"
        "For each: numbered bounding-box overlays show what VaultLab identified + "
        "where on the figure. Right-side callouts are short tags; full explanations "
        "live in the speaker notes.\n\n"
        f"Generated 2026-04-29 by vaultlab figure-understanding prototype "
        f"(scripts/figure_understanding_prototype.py)."
    )
    for i, line in enumerate(sub_text.split("\n\n")):
        p = sf.paragraphs[0] if i == 0 else sf.add_paragraph()
        run = p.add_run()
        run.text = line
        run.font.name = "Arial"
        run.font.size = Pt(18)
        run.font.color.rgb = RGBColor(60, 60, 60)

    # Figure slides
    for plan, ann_path in zip(plans, annotated_paths):
        s = pres.slides.add_slide(blank)

        # Title
        title_box = s.shapes.add_textbox(
            Inches(0.4), Inches(0.2), Inches(12.5), Inches(0.7)
        )
        tf = title_box.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        run = p.add_run()
        run.text = plan.title
        run.font.name = "Arial"
        run.font.size = Pt(22)
        run.font.bold = True
        run.font.color.rgb = RGBColor(20, 20, 20)

        # Annotated figure — compute size from image aspect to fit available area
        avail_w_in = 12.5
        avail_h_in = 5.6
        img = Image.open(ann_path)
        img_w, img_h = img.size
        aspect = img_w / img_h
        avail_aspect = avail_w_in / avail_h_in
        if aspect > avail_aspect:
            disp_w = Inches(avail_w_in)
            disp_h = Inches(avail_w_in / aspect)
        else:
            disp_h = Inches(avail_h_in)
            disp_w = Inches(avail_h_in * aspect)

        x_in = (13.333 - disp_w / Emu(914400)) / 2  # center
        s.shapes.add_picture(
            str(ann_path),
            Inches(x_in),
            Inches(1.0),
            width=disp_w,
            height=disp_h,
        )

        # Caption
        caption_box = s.shapes.add_textbox(
            Inches(0.4), Inches(6.7), Inches(12.5), Inches(0.7)
        )
        cf = caption_box.text_frame
        cf.word_wrap = True
        p = cf.paragraphs[0]
        run = p.add_run()
        run.text = plan.overall_caption
        run.font.name = "Arial"
        run.font.size = Pt(13)
        run.font.italic = True
        run.font.color.rgb = RGBColor(60, 60, 60)

        # Speaker notes
        notes = s.notes_slide.notes_text_frame
        ann_listing = "\n\nNumbered annotations:\n" + "\n".join(
            f"{i + 1}. [{a.label}] — {a.explanation}"
            for i, a in enumerate(plan.annotations)
        )
        notes.text = plan.long_explanation + ann_listing

    # Provenance
    try:
        pres.core_properties.comments = (
            "Generated by vaultlab figure-understanding prototype. "
            "Source: car_t_30min_v13.pptx. Annotations are vaultlab's "
            "visual interpretation; full explanation in speaker notes."
        )
    except (AttributeError, ValueError):
        pass

    PPTX_OUT.parent.mkdir(parents=True, exist_ok=True)
    pres.save(PPTX_OUT)
    return PPTX_OUT


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    annotated_paths: list[Path] = []
    for plan in PLANS:
        out = annotate_figure(plan)
        print(f"Annotated -> {out}")
        annotated_paths.append(out)

    pptx_path = build_pptx(PLANS, annotated_paths)
    print(f"\nPPTX written -> {pptx_path}")


if __name__ == "__main__":
    main()
