"""Frontmatter-first KB retrieval.

This is layer 2 of the canonical "researcher pathway" cascade documented in
``vaultlab/kb/retrieve.md``:

    corpus  →  frontmatter  →  indexes  →  wikilink walk  →  cumulative recall
              ^^^^^^^^^^^^^

A human researcher who knows a project well doesn't grep blind — they filter
by structured metadata first (type, project, donor, date, status) and only
*then* drill into bodies. :func:`retrieve_by_frontmatter` is that primitive.

Design notes
------------
- ``filter`` is a dict mapping frontmatter key → expected value. Values can be:

  * a scalar (string / int / etc.) — exact equality match.
  * a ``set`` — OR semantics: file matches if the frontmatter value is in the
    set, or if any item of a list-valued frontmatter field is in the set.

  Across keys, semantics are AND: the file must satisfy every key in the
  filter to be returned.

- Files without YAML frontmatter are silently skipped. This is intentional —
  the researcher-pathway cascade falls back to semantic search and wikilink
  walks for unfrontmattered notes; this primitive just does the structured
  layer.

- The auto-index files themselves (``_Index.md``, ``_Catalog.md``,
  ``_BackLinks.md``) are skipped so callers don't get them as matches.

- Dotfile directories (``.obsidian/``, ``.embeddings/``) are skipped, matching
  the convention used elsewhere in ``vaultlab.kb``.

Examples
--------
>>> from vaultlab.kb.retrieve import retrieve_by_frontmatter  # doctest: +SKIP
>>> # All wiki concept notes for the metabolism project
>>> paths = retrieve_by_frontmatter(
...     {"type": "wiki", "project": "metabolism"},
...     kb_root=Path("G:/My Drive/Knowledge/metabolism"),
... )  # doctest: +SKIP
>>> # Notes tagged with either 'lipidomics' OR 'maldi'
>>> paths = retrieve_by_frontmatter(
...     {"tags": {"lipidomics", "maldi"}},
...     kb_root=Path("G:/My Drive/Knowledge/metabolism"),
... )  # doctest: +SKIP
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import frontmatter  # python-frontmatter, dep from pyproject.toml

__all__ = ["retrieve_by_frontmatter"]


# Index files auto-generated by :func:`vaultlab.kb.indexes.build_indexes`.
# These get excluded from frontmatter retrieval so callers don't get
# meta-pages back as content matches.
_INDEX_BASENAMES = frozenset({"_Index.md", "_Catalog.md", "_BackLinks.md"})


def retrieve_by_frontmatter(
    filter: dict[str, Any],
    kb_root: str | Path,
) -> list[Path]:
    """Return all markdown files under ``kb_root`` whose YAML frontmatter
    matches ``filter``.

    Parameters
    ----------
    filter
        Key → expected-value mapping. AND across keys; if value is a ``set``,
        OR within that key. List-valued frontmatter fields (e.g. ``tags: [a,
        b]``) are membership-tested.
    kb_root
        Root folder of the knowledge base. Walked recursively.

    Returns
    -------
    list[Path]
        Sorted list of paths matching every filter clause. Empty if no
        matches or ``kb_root`` doesn't exist.
    """
    root = Path(kb_root)
    if not root.exists():
        return []

    matches: list[Path] = []
    for path in root.rglob("*.md"):
        # Skip dotfile directories (.obsidian, .embeddings, etc.)
        if any(part.startswith(".") for part in path.relative_to(root).parts):
            continue
        # Skip the auto-index files themselves.
        if path.name in _INDEX_BASENAMES:
            continue

        meta = _load_frontmatter(path)
        if meta is None:
            # No frontmatter → skip (per spec).
            continue

        if _matches(meta, filter):
            matches.append(path)

    matches.sort()
    return matches


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _load_frontmatter(path: Path) -> dict[str, Any] | None:
    """Load YAML frontmatter from ``path``.

    Returns ``None`` if the file has no frontmatter block or it failed to
    parse. We're deliberately tolerant here — a malformed YAML block is
    treated like "no frontmatter" rather than raising, because the
    retrieval cascade falls back to other layers for ambiguous files.
    """
    try:
        post = frontmatter.load(path)
    except (OSError, Exception):  # noqa: BLE001 - tolerant by design
        return None
    # python-frontmatter returns an empty metadata dict for files with no
    # frontmatter block; treat that as "no frontmatter" so callers can rely
    # on the documented skip behavior.
    if not post.metadata:
        return None
    return dict(post.metadata)


def _matches(meta: dict[str, Any], filter: dict[str, Any]) -> bool:
    """Return True iff ``meta`` satisfies every clause in ``filter``."""
    for key, expected in filter.items():
        if key not in meta:
            return False
        actual = meta[key]
        if not _clause_matches(actual, expected):
            return False
    return True


def _clause_matches(actual: Any, expected: Any) -> bool:
    """Single-key match: AND across keys is the caller's job."""
    # Filter expects "any of these" (OR semantics within this key).
    if isinstance(expected, set):
        if isinstance(actual, list):
            return any(item in expected for item in actual)
        return actual in expected

    # Filter is a scalar. If frontmatter value is a list (e.g. tags), check
    # membership; otherwise compare equality.
    if isinstance(actual, list):
        return expected in actual
    return actual == expected
