"""Figure-in-markdown report generator.

Bobby's 2026-04-29 ask: produce review-friendly markdown reports that bundle
figures with captions + result-section explanations, openable in Obsidian
for the user to review.

The report is one markdown file with embedded figure references. Each entry
has: figure (relative path or absolute), caption, optional results paragraph,
optional notes for further work. The file is laid out so reviewers can scroll
through everything in one Obsidian tab.

Public API
----------

- :class:`FigureEntry` — dataclass for one (figure, caption, results) bundle
- :class:`RenderResult` — the render outcome: report path, figures dir,
  entry count, and an ``open_command`` (a ``bobby-kb open`` string the caller
  can print so the user opens the report in Obsidian)
- :func:`render_report` — write the markdown file (and copy figures into a
  sibling ``figures/`` folder if requested); returns a :class:`RenderResult`

Examples
--------

>>> from pathlib import Path
>>> from vaultlab.figures.report import FigureEntry, render_report
>>> entries = [
...     FigureEntry(
...         figure="path/to/fig1.png",
...         caption="UMAP colored by cluster.",
...         results="Three populations resolve at resolution=0.5; cluster 2 enriched in CD8+ markers.",
...     ),
...     FigureEntry(
...         figure="path/to/fig2.png",
...         caption="Marker dot-plot per cluster.",
...         results="Cluster 2 expresses GZMK + CCL5 → consistent with effector memory CD8 T cells.",
...         notes="Confirm with TCR-seq overlap if available.",
...     ),
... ]
>>> render_report(  # doctest: +SKIP
...     entries=entries,
...     output_path="/g/My Drive/Knowledge/research/Output/2026-04-29-cluster-review.md",
...     title="Cluster review — 2026-04-29",
... )
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path


@dataclass
class FigureEntry:
    """One figure + the user-facing context about it.

    Attributes
    ----------
    figure
        Path to the figure file (PNG / JPG / SVG / PDF). Absolute or relative;
        resolved against ``working_dir`` at render time.
    caption
        Short caption rendered directly under the figure (italicized).
    results
        Optional paragraph explaining what the figure shows + the analytic
        result the user should take away. Rendered under "## Results" subsection.
    notes
        Optional follow-up / open-questions paragraph rendered under "## Notes".
    title
        Optional override for the section heading; defaults to the figure
        stem turned into Title Case.
    """

    figure: str
    caption: str = ""
    results: str = ""
    notes: str = ""
    title: str = ""


@dataclass
class RenderResult:
    """Outcome of rendering — file paths the caller can act on."""

    report_path: Path
    figures_dir: Path | None
    n_entries: int
    open_command: str = ""


def render_report(
    *,
    entries: list[FigureEntry],
    output_path: str | Path,
    title: str,
    description: str = "",
    working_dir: str | Path | None = None,
    copy_figures: bool = True,
    figures_subdir: str = "figures",
) -> RenderResult:
    """Write a figure-review markdown report.

    Parameters
    ----------
    entries
        The figures + captions + results paragraphs to bundle.
    output_path
        Path to write the markdown file (parents created as needed).
    title
        Report title (rendered as the H1; appears in frontmatter).
    description
        Optional one-paragraph summary at the top.
    working_dir
        Used to resolve relative figure paths. If ``None``, ``output_path``'s
        parent is used.
    copy_figures
        If ``True`` (default), copy each figure into ``<output_dir>/<figures_subdir>/``
        so the report is portable. If ``False``, embed paths as-given (caller
        guarantees the figures exist relative to the markdown file).
    figures_subdir
        Where copied figures land relative to the report.

    Returns
    -------
    RenderResult
        Paths + an ``open_command`` string suitable for printing to the user.
    """
    if not entries:
        raise ValueError("render_report requires at least one FigureEntry")

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    base_dir = Path(working_dir) if working_dir is not None else out.parent
    figures_dir: Path | None = None
    if copy_figures:
        figures_dir = out.parent / figures_subdir
        figures_dir.mkdir(parents=True, exist_ok=True)

    body_parts: list[str] = []
    body_parts.append(_render_frontmatter(title=title, n=len(entries)))
    body_parts.append(f"# {title}\n")
    if description.strip():
        body_parts.append(f"\n{description.strip()}\n")
    body_parts.append(
        "\n> Auto-generated by `vaultlab.figures.report`. Scroll through the "
        "figures below; edit the **Notes** sections to flag follow-ups.\n"
    )

    for i, entry in enumerate(entries, start=1):
        section_title = entry.title or _humanize(Path(entry.figure).stem) or f"Figure {i}"
        body_parts.append(f"\n---\n\n## {i}. {section_title}\n")

        # Resolve + optionally copy the figure
        rendered_path = _resolve_figure(
            entry.figure,
            base_dir=base_dir,
            target_dir=figures_dir,
            output_dir=out.parent,
        )
        body_parts.append(f"\n![{section_title}]({rendered_path})\n")

        if entry.caption.strip():
            body_parts.append(f"\n*{entry.caption.strip()}*\n")

        if entry.results.strip():
            body_parts.append("\n### Results\n")
            body_parts.append(f"\n{entry.results.strip()}\n")

        if entry.notes.strip():
            body_parts.append("\n### Notes\n")
            body_parts.append(f"\n{entry.notes.strip()}\n")

    out.write_text("".join(body_parts), encoding="utf-8")

    open_command = f"bobby-kb open {out.stem}"

    return RenderResult(
        report_path=out,
        figures_dir=figures_dir,
        n_entries=len(entries),
        open_command=open_command,
    )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _render_frontmatter(*, title: str, n: int) -> str:
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d")
    return (
        "---\n"
        f"title: {title}\n"
        "type: figure-report\n"
        "managed_by: vaultlab.figures.report\n"
        f"created: {timestamp}\n"
        f"n_figures: {n}\n"
        "---\n"
    )


def _resolve_figure(
    figure: str,
    *,
    base_dir: Path,
    target_dir: Path | None,
    output_dir: Path,
) -> str:
    """Locate the figure file; optionally copy into target_dir.

    Returns the path string to embed in the markdown — relative to the report
    file when possible, absolute otherwise.
    """
    candidate = Path(figure)
    if not candidate.is_absolute():
        candidate = base_dir / candidate
    candidate = candidate.resolve()

    if not candidate.exists():
        # Don't crash report generation — embed the path as-given so the
        # user can fix it manually. Could log a warning here.
        return figure

    if target_dir is None:
        # Relative to output_dir if possible
        try:
            rel = candidate.relative_to(output_dir)
            return rel.as_posix()
        except ValueError:
            return candidate.as_posix()

    # Copy + dedupe (use stem + counter if collision)
    target_name = candidate.name
    target_path = target_dir / target_name
    if target_path.exists() and not target_path.samefile(candidate):
        # Resolve name collision
        stem = candidate.stem
        suffix = candidate.suffix
        counter = 1
        while True:
            candidate_name = f"{stem}-{counter}{suffix}"
            target_path = target_dir / candidate_name
            if not target_path.exists():
                break
            counter += 1
    if not target_path.exists():
        shutil.copy2(candidate, target_path)
    rel = target_path.relative_to(output_dir).as_posix()
    return rel


def _humanize(stem: str) -> str:
    """Turn ``cluster_umap_v3`` into ``Cluster Umap V3``."""
    words = stem.replace("_", " ").replace("-", " ").split()
    return " ".join(w.capitalize() for w in words)


__all__ = ["FigureEntry", "RenderResult", "render_report"]
